### ISSUE TITLE
Im here to helpsies

### ISSUE THREAD

**Issue by TacoNoBurrito** [AgaricaGamer/MiniOres_Trial#1]
Hallo

I made a practice server awhile back.

I had a rush gamemode and in rush blocks despawn after 15 seconds of placing.

Heres the code. I think i would help

Import These:
use pocketmine\block\Block;
use pocketmine\scheduler\ClosureTask;

Code:

(this has random stuff btw because i used it in my old server)
ALSO replace Main::getInstance() with $this or $this->plugin depending on how u do it

 public function onPlace(BlockPlaceEvent $event) {
        $player = $event->getPlayer();
        $block = $event->getBlock();
        if ($event->getBlock()->getId() == 24) {
                Main::getInstance()->getScheduler()->scheduleDelayedTask(new ClosureTask(
                    function (int $currentTick) use ($block): void {
                        $level = $block->getLevel();
                        // block to change to
                        $level->setBlock(new Vector3($block->x, $block->y, $block->z), Block::get(Block::AIR));
                    }
                // 15 * 20 = 15 seconds
                ), 15 * 20);
        }else{
            if ($player->isOp()) return;
            $event->setCancelled(true);
            return true;
        }
    }

**Comment by AgaricaGamer** [comment]
Thank You For Helping Me
 Because I am Just A Begginner
I will use These codes.

Sincerely Thanks.
